"""Core Doctor orchestrator — runs the agentic diagnosis loop."""
from __future__ import annotations
from typing import List, Optional, Dict, Any
from .config import RagDoctorConfig
from .connectors.base import Document, PipelineConnector
from .tools import (
    ChunkAnalyzer, RetrievalAuditor, PositionTester,
    HallucinationTracer, ChunkOptimizer, QueryRewriter,
    ToolResult,
)
from .report import DiagnosisReport, SEVERITY_RANK


class Doctor:
    """
    Orchestrates the six diagnostic tools in a rule-based agent loop.

    Decision tree:
      1. RetrievalAuditor — if retrieval miss → RC-1 / RC-5
      2. PositionTester   — if position bias → RC-2
      3. ChunkAnalyzer    — if fragmentation → RC-3
      4. HallucinationTracer — if low faithfulness → RC-4
      5. QueryRewriter    — called if RC-1/5 to try fixes
      6. ChunkOptimizer   — called if RC-3 to find best strategy
    """

    def __init__(self, config: RagDoctorConfig, connector: Optional[PipelineConnector] = None):
        self.config = config
        self.connector = connector
        cfg = config.diagnosis

        self._chunk_analyzer    = ChunkAnalyzer(coherence_threshold=cfg.coherence_threshold)
        self._retrieval_auditor = RetrievalAuditor(recall_threshold=cfg.recall_threshold)
        self._position_tester   = PositionTester()
        self._hallucination_tracer = HallucinationTracer(faithfulness_threshold=cfg.faithfulness_threshold)
        self._chunk_optimizer   = ChunkOptimizer()
        self._query_rewriter    = QueryRewriter()

    @classmethod
    def from_config(cls, path: str, connector: Optional[PipelineConnector] = None) -> "Doctor":
        return cls(RagDoctorConfig.from_yaml(path), connector)

    @classmethod
    def default(cls, connector: Optional[PipelineConnector] = None) -> "Doctor":
        return cls(RagDoctorConfig.default(), connector)

    def diagnose(
        self,
        query: str,
        answer: str,
        docs: Optional[List[Document]] = None,
        expected: Optional[str] = None,
        corpus_texts: Optional[List[str]] = None,
    ) -> DiagnosisReport:
        """
        Run the full agentic diagnosis loop.

        Args:
            query:        The user's original query
            answer:       The answer generated by the RAG pipeline
            docs:         Retrieved documents (if available)
            expected:     Ground-truth answer (optional but improves diagnosis)
            corpus_texts: Full document corpus for chunk optimization
        """
        tool_results: List[ToolResult] = []
        cfg = self.config.diagnosis

        # If no docs provided, try to retrieve them
        if docs is None and self.connector:
            docs = self.connector.retrieve(query, top_k=self.config.retrieval.top_k)
        docs = docs or []

        # ── Step 1: Retrieval Audit ──────────────────────────────────────────
        retrieval_result = self._retrieval_auditor.run(docs=docs, expected=expected, query=query)
        tool_results.append(retrieval_result)

        retrieval_miss = not retrieval_result.passed
        best_position  = retrieval_result.details.get("best_match_position", 0)

        # ── Step 2: Position Test (only if retrieval succeeded) ──────────────
        position_result = None
        if not retrieval_miss and cfg.position_tester:
            position_result = self._position_tester.run(
                docs=docs, best_position=best_position, top_k=len(docs)
            )
            tool_results.append(position_result)

        # ── Step 3: Chunk Analysis ────────────────────────────────────────────
        chunk_result = None
        if cfg.chunk_analyzer:
            chunk_result = self._chunk_analyzer.run(docs=docs, query=query)
            tool_results.append(chunk_result)

        # ── Step 4: Hallucination Tracing ─────────────────────────────────────
        hallucination_result = None
        if cfg.hallucination_tracer:
            hallucination_result = self._hallucination_tracer.run(answer=answer, docs=docs)
            tool_results.append(hallucination_result)

        # ── Step 5: Query Rewriter (if retrieval miss) ────────────────────────
        rewrite_result = None
        if retrieval_miss and cfg.query_rewriter:
            rewrite_result = self._query_rewriter.run(
                query=query,
                original_docs=docs,
                connector=self.connector,
                expected=expected,
                top_k=self.config.retrieval.top_k,
            )
            tool_results.append(rewrite_result)

        # ── Step 6: Chunk Optimizer (if fragmentation detected) ───────────────
        optimizer_result = None
        if chunk_result and not chunk_result.passed and corpus_texts and cfg.chunk_optimizer:
            test_pairs = []
            if expected and query:
                test_pairs = [{"query": query, "expected": expected}]
            if test_pairs:
                optimizer_result = self._chunk_optimizer.run(
                    corpus_texts=corpus_texts,
                    test_pairs=test_pairs,
                    current_strategy={
                        "strategy": self.config.chunking.strategy,
                        "chunk_size": self.config.chunking.chunk_size,
                        "chunk_overlap": self.config.chunking.chunk_overlap,
                    },
                )
                tool_results.append(optimizer_result)

        # ── Determine Root Cause ──────────────────────────────────────────────
        root_cause, severity, finding, fix, patch = self._determine_root_cause(
            retrieval_result=retrieval_result,
            position_result=position_result,
            chunk_result=chunk_result,
            hallucination_result=hallucination_result,
            rewrite_result=rewrite_result,
            optimizer_result=optimizer_result,
        )

        return DiagnosisReport(
            query=query,
            answer=answer,
            expected=expected,
            root_cause=root_cause,
            severity=severity,
            finding=finding,
            tool_results=tool_results,
            fix_suggestion=fix,
            config_patch=patch,
        )

    def _determine_root_cause(
        self,
        retrieval_result,
        position_result,
        chunk_result,
        hallucination_result,
        rewrite_result,
        optimizer_result,
    ):
        """Rule-based root cause attribution."""
        fix = None
        patch = {}

        # RC-1 / RC-5: Retrieval miss
        if retrieval_result and not retrieval_result.passed:
            if rewrite_result and not rewrite_result.passed:
                # Rewrite helped → vocabulary mismatch
                root_cause = "query_mismatch"
                severity = "high"
                finding = "Query vocabulary doesn't match document vocabulary. Rewrite improved recall."
                fix = rewrite_result.recommendation
            else:
                root_cause = "retrieval_miss"
                severity = "high"
                finding = retrieval_result.finding
                fix = retrieval_result.recommendation
            return root_cause, severity, finding, fix, patch

        # RC-2: Position bias
        if position_result and not position_result.passed:
            root_cause = "context_position_bias"
            severity = position_result.severity
            finding = position_result.finding
            fix = position_result.recommendation
            patch = {"retrieval.reranker": True}
            return root_cause, severity, finding, fix, patch

        # RC-3: Chunk fragmentation
        if chunk_result and not chunk_result.passed:
            root_cause = "chunk_fragmentation"
            severity = chunk_result.severity
            finding = chunk_result.finding
            fix = chunk_result.recommendation
            if optimizer_result and not optimizer_result.passed:
                details = optimizer_result.details
                ranked = details.get("ranked_strategies", [])
                if ranked:
                    best = ranked[0]
                    patch = {
                        "chunking.strategy": best["strategy"],
                        "chunking.chunk_size": best["chunk_size"],
                        "chunking.chunk_overlap": best["chunk_overlap"],
                    }
                    fix = optimizer_result.recommendation or fix
            return root_cause, severity, finding, fix, patch

        # RC-4: Hallucination
        if hallucination_result and not hallucination_result.passed:
            root_cause = "hallucination"
            severity = hallucination_result.severity
            finding = hallucination_result.finding
            fix = hallucination_result.recommendation
            return root_cause, severity, finding, fix, patch

        # All tools passed
        worst_severity = "low"
        for tr in [retrieval_result, position_result, chunk_result, hallucination_result]:
            if tr and SEVERITY_RANK.get(tr.severity, 0) > SEVERITY_RANK.get(worst_severity, 0):
                worst_severity = tr.severity

        return "healthy", worst_severity, "No significant issues detected. Pipeline appears healthy.", None, {}

    def batch_diagnose(self, test_cases: List[dict]) -> List[DiagnosisReport]:
        """Run diagnosis on a batch of test cases."""
        reports = []
        for case in test_cases:
            report = self.diagnose(
                query=case.get("query", ""),
                answer=case.get("answer", ""),
                docs=case.get("docs"),
                expected=case.get("expected"),
                corpus_texts=case.get("corpus_texts"),
            )
            reports.append(report)
        return reports
